[package]
name = 'do0ir_cli'
version = '0.5.0'
authors = ['Mohammad Javad Ghasemy <geeksesi@gmail.com>']
edition = '2018'

[dependencies]
reqwest = '0.9.22'
serde = '1.0'
serde_json = '1.0'
clipboard = '0.5.0'
