[package]
name = 'do0ir_cli'
version = '2.0.0'
authors = ['Mohammad Javad Ghasemy <geeksesi@gmail.com>']
edition = '2018'

[dependencies]
reqwest = '*'
serde = '*'
serde_json = '*'
clipboard = '*'
hotkey = '*'
notifica = '*'